### ISSUE TITLE
consumable demo components

### ISSUE THREAD

**Issue by alialkhalidi** [trustbloc/sandbox#991]
issuer, rp, login-consent, and ace-rp kustomize base can not be consumed outside of the repo workflow because it points to a non-existing tag `latest`. The latter gets build as part of the local development workflow, but does not persist beyond that.

the paradigm for kustomize base, or any overlay for that matter, is that its a "working" consumable artifact.

accordingly, the image tag in base and the default tag in the Makefile should match a working and accessible tag, and renders a running deployment. To accommodate for the change in the local development workflow, we can add an override to the local overlay specifying latest as the tag, example:
```
overlays/local/issuer/kustomization.yaml:
patchesStrategicMerge:
- modify-image.yml

overlays/local/issuer/modify-image.yml:
kind: Deployment
apiVersion: apps/v1
metadata:
  name: issuer
spec:
  template:
    spec:
      containers:
      - name: issuer
        image: ghcr.io/trustbloc-cicd/sandbox-issuer:latest
```
